---
- hosts: all
  become: true
  remote_user: "{{ target_user }}"
  tasks:
    - name: Create Docker group
      ansible.builtin.group:
        name: docker
        state: present
    
    - name: Add Your user to Docker group
      ansible.builtin.user:
        name: "{{ target_user }}"
        groups: docker
        append: yes
        state: present